#COMO LIDAR COM ATRIBUTOS QUE MUDAM?
#1 - ELEMENTOS MUDAM, PRINCIPALMENTE EM REDE SOCIAS E SITES COM MUITO TRAFEGO
#2 - TEM QUE ESTAR MONITORANDO SUAS AUTOMAÇÕES 
            # - TENHA TRATAMENTO DE EXEÇÕES
            # - SISTEMAS DE LOG
                #- A CADA ERRO É NOTIFICADO NO SISTEMA

#3 - TENHA SEMPRE TRATAMENTO DE ERROS, PARA QUE ERROS NAO FIQUEM EXPOSTOS AO USUARIOS DA AUTOMAÇÃO  